PACKAGE_NAME="realtek-r8125"
PACKAGE_VERSION="9.016.01"
BUILT_MODULE_NAME[0]="r8125"
DEST_MODULE_LOCATION[0]="/kernel/drivers/net/ethernet/realtek"
AUTOINSTALL="yes"
MAKE[0]="make KVER=${kernelver} BSRC=/lib/modules/${kernelver}"
CLEAN="make KVER=${kernelver} BSRC=/lib/modules/${kernelver} clean"
